### ISSUE TITLE
What advantages does this have over a plain AppImage?

### ISSUE THREAD

**Issue by probonopd** [Elfsetup/elfsetup#1]
Please clarify, what advantages does this have over a plain AppImage?

It is not recommended (nor needed) to put AppImages into an archive or "installer". Part of their beauty is that you don't need to unpack or install them, and the optional `appimaged` daemon which handles desktop integration relies on this.

**Comment by Elfsetup** [comment]
AppImage is amazing, some people want install and uninstall icons and launcher in a easy manner, not daemons. When you install an application on MacOS you install a pack similar to AppImage and you are put all this application in a special folder "Applications". if you run an AppImage and move the AppImage file the launcher will stop work!. But Nixsetup is not oriented to AppImage only, its a great help with others app like Vala, Tcl/Tk, PyGTK, etc. Imaging a Perl/Gtk2, you will get a app.pl, how to integrate into system in a good looking manner??.. Nixsetup does these things.

**Comment by probonopd** [comment]
> if you run an AppImage and move the AppImage file the launcher will stop work!

Not if you are running the `appimaged` daemon. macOS has something similar called "LaunchServices" as part of the operating system.

**Comment by Elfsetup** [comment]
Not daemon, Do you need a Daemon for What??. A permanent use of memory for What??.Give me a good reason!.  Free the memory for an apache or other.. You are destroying the dependencies headeache, that is AMAZING!!. Do not waste with a daemon occupy memory!..

**Comment by probonopd** [comment]
I can see that this can have advantages for other types of files but not for AppImages. So it would be best not to mention AppImage in conjunction with this project.

**Comment by Elfsetup** [comment]
ok, will be retired.
