### ISSUE TITLE
Relation to Nix / NixOS

### ISSUE THREAD

**Issue by waldyrious** [Elfsetup/elfsetup#2]
What's the reasoning behind the name of this project? Is it related somehow (based on, inspired by...) the Nix package manager or the corresponding NixOS distro? If not, I'd suggest reconsidering the name, as it may generate some confusion unnecessarily.

**Comment by Elfsetup** [comment]
No link with Nix OS, app was renamed..

**Comment by Elfsetup** [comment]
No link with Nix OS, app was renamed..

**Comment by waldyrious** [comment]
For future reference, the previous name was "Nixsetup". Interestingly, "Elfsetup" is *still* vaguely reminiscent of NixOS (see [NixOS/patchelf](https://github.com/NixOS/patchelf)), but that doesn't sound as such a big deal IMO.

In any case, I am generally curious as to what criteria are being used for the names -- are you just picking cool-sounding names, or is there a specific reason to have used the "nix-" and "elf-" prefixes?
